/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchRouteImport } from './routes/arch'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as MapRouteImport } from './routes/map'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ReviewRouteImport } from './routes/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchRoute = ArchRouteImport.update({
  id: '/arch',
  path: '/arch',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arch': typeof ArchRoute
  '/catalog': typeof CatalogRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/guide': typeof GuideRoute
  '/map': typeof MapRoute
  '/offline': typeof OfflineRoute
  '/preview': typeof PreviewRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arch': typeof ArchRoute
  '/catalog': typeof CatalogRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/guide': typeof GuideRoute
  '/map': typeof MapRoute
  '/offline': typeof OfflineRoute
  '/preview': typeof PreviewRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arch': typeof ArchRoute
  '/catalog': typeof CatalogRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/guide': typeof GuideRoute
  '/map': typeof MapRoute
  '/offline': typeof OfflineRoute
  '/preview': typeof PreviewRoute
  '/review': typeof ReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arch'
    | '/catalog'
    | '/developers'
    | '/discover'
    | '/guide'
    | '/map'
    | '/offline'
    | '/preview'
    | '/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arch'
    | '/catalog'
    | '/developers'
    | '/discover'
    | '/guide'
    | '/map'
    | '/offline'
    | '/preview'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/arch'
    | '/catalog'
    | '/developers'
    | '/discover'
    | '/guide'
    | '/map'
    | '/offline'
    | '/preview'
    | '/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchRoute: typeof ArchRoute
  CatalogRoute: typeof CatalogRoute
  DevelopersRoute: typeof DevelopersRoute
  DiscoverRoute: typeof DiscoverRoute
  GuideRoute: typeof GuideRoute
  MapRoute: typeof MapRoute
  OfflineRoute: typeof OfflineRoute
  PreviewRoute: typeof PreviewRoute
  ReviewRoute: typeof ReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arch': {
      id: '/arch'
      path: '/arch'
      fullPath: '/arch'
      preLoaderRoute: typeof ArchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchRoute: ArchRoute,
  CatalogRoute: CatalogRoute,
  DevelopersRoute: DevelopersRoute,
  DiscoverRoute: DiscoverRoute,
  GuideRoute: GuideRoute,
  MapRoute: MapRoute,
  OfflineRoute: OfflineRoute,
  PreviewRoute: PreviewRoute,
  ReviewRoute: ReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
