# The NEW private review bucket. This is the ONLY bucket this config creates.
#
# Restricted-serving requirements (warehouse#16):
#   - public_access_prevention = "enforced"  -> allUsers/allAuthenticatedUsers can NEVER be granted
#   - uniform_bucket_level_access             -> no per-object ACLs to leak through
#   - NO CDN backend bucket points at it (see iap.tf: it is served only via the IAP Cloud Run app)
#
# Destroy-proofing (SAFETY CONTRACT #2):
#   - force_destroy = false      -> tofu refuses to delete a non-empty bucket
#   - prevent_destroy = true     -> tofu errors on ANY plan that would destroy this bucket
resource "google_storage_bucket" "review" {
  name     = var.review_bucket
  project  = var.project_id
  location = var.region
  labels   = var.labels

  public_access_prevention    = "enforced"
  uniform_bucket_level_access = true
  force_destroy               = false

  # Restricted artifacts are regenerated by the ingest job; keep a short version safety net
  # rather than relying on it as a source of truth.
  versioning {
    enabled = true
  }

  # Signed URLs from /api/review-catalog (review_catalog.py) point straight at
  # storage.googleapis.com — maplibre's PMTiles range-reads and duckdb-wasm's GeoParquet reads
  # fetch them cross-origin from the hazards-review app, so the bucket (not just review-api) needs
  # CORS. GET/HEAD only — signed URLs are already scoped read-only and short-TTL; no state-changing
  # verb ever hits GCS directly. Response headers cover Range reads specifically (PMTiles/GeoParquet
  # depend on Content-Range/Accept-Ranges to do partial fetches).
  #
  # Mirrors the exact origins already live on review-api's REVIEW_CORS_ORIGINS
  # (infra/serving-review-api.tf) — same app, same trust boundary, kept in sync deliberately.
  #
  # GAP: review-api's CORS also allows REVIEW_CORS_ORIGIN_REGEX (Firebase preview-channel URLs,
  # `ut-dnr-ugs-maps-(prod|dev)--*.web.app`) via FastAPI's regex support. GCS bucket `cors{}` has
  # no regex/wildcard-subdomain matching (origin must be a literal string or bare "*") — a preview
  # channel's XHR to /api/* will work, but its browser fetch of a signed PMTiles/parquet URL will
  # fail CORS. No fix here short of "*" (too broad for a private bucket) or listing exact preview
  # URLs (they're dynamic, generated per-PR). Acceptable for now: prod + dev + localhost cover the
  # real smoke test and steady-state use; revisit if preview-channel review-catalog rendering is
  # actually needed.
  cors {
    origin          = ["https://maps.geology.utah.gov", "https://ut-dnr-ugs-maps-prod.web.app", "https://ut-dnr-ugs-maps-prod.firebaseapp.com", "https://ut-dnr-ugs-maps-dev.web.app", "https://ut-dnr-ugs-maps-dev.firebaseapp.com", "http://localhost:5173"]
    method          = ["GET", "HEAD"]
    response_header = ["Content-Type", "Range", "Content-Range", "Accept-Ranges", "Content-Length"]
    max_age_seconds = 3600
  }

  lifecycle {
    prevent_destroy = true
  }
}
