# The NEW private review bucket. This is the ONLY bucket this config creates.
#
# Restricted-serving requirements (warehouse#16):
#   - public_access_prevention = "enforced"  -> allUsers/allAuthenticatedUsers can NEVER be granted
#   - uniform_bucket_level_access             -> no per-object ACLs to leak through
#   - NO CDN backend bucket points at it (see iap.tf: it is served only via the IAP Cloud Run app)
#
# Destroy-proofing (SAFETY CONTRACT #2):
#   - force_destroy = false      -> tofu refuses to delete a non-empty bucket
#   - prevent_destroy = true     -> tofu errors on ANY plan that would destroy this bucket
resource "google_storage_bucket" "review" {
  name     = var.review_bucket
  project  = var.project_id
  location = var.region
  labels   = var.labels

  public_access_prevention    = "enforced"
  uniform_bucket_level_access = true
  force_destroy               = false

  # Restricted artifacts are regenerated by the ingest job; keep a short version safety net
  # rather than relying on it as a source of truth.
  versioning {
    enabled = true
  }

  # The browser fetches the SIGNED review-asset URLs (pmtiles/geoparquet) DIRECTLY from
  # storage.googleapis.com, cross-origin and with Range — a request that never reaches review-api, so
  # the app's own CORS middleware does NOT cover it; the BUCKET must allow these origins itself. Same
  # fixed origins as var.review_cors_origins (GCS CORS can't express the regex preview channels, so only
  # the literal list). `Range` must be in response_header so the preflight echoes it in
  # Access-Control-Allow-Headers (Range makes the GET non-simple → preflighted) and the 206 headers are
  # exposed to JS.
  cors {
    origin          = split(",", var.review_cors_origins)
    method          = ["GET", "HEAD"]
    response_header = ["Content-Type", "Range", "Content-Range", "Accept-Ranges", "Content-Length"]
    max_age_seconds = 3600
  }

  lifecycle {
    prevent_destroy = true
  }
}
